BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"
BBFILE_COLLECTIONS += "dace-hybris-layer"
BBFILE_PATTERN_dace-hybris-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_dace-hybris-layer = "8"
LAYERSERIES_COMPAT_dace-hybris-layer = "walnascar"
