#!/bin/sh

# Fixes some battery drain and the deep sleep mode
cat /dev/spm

# Set the CPU's freq to 787MHz and disable three cores
echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 0        > /sys/devices/system/cpu/cpu1/online
echo 0        > /sys/devices/system/cpu/cpu2/online
echo 0        > /sys/devices/system/cpu/cpu3/online
