#!/bin/sh

# Set the CPU governor and disable the second core
# TODO: this watch is a bit sluggish. Figure out if tweaks to CPU and GPU can improve this. Currently disabling second core for power efficiency.
echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 0        > /sys/module/lpm_levels/parameters/sleep_disabled
echo 0        > /sys/devices/system/cpu/cpu1/online

