#!/bin/sh
set -e

# Enable low power mode
echo 0 > /sys/module/lpm_levels/parameters/sleep_disabled

# Set CPU governor to ondemand (ramps up quickly for bursty workloads)
echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

# Disable three cores
echo 0 > /sys/devices/system/cpu/cpu1/online
echo 0 > /sys/devices/system/cpu/cpu2/online
echo 0 > /sys/devices/system/cpu/cpu3/online

