#!/bin/sh

# Medaka expects a wifi mac address in /persist, but doesn't actually have a per
# put a file in persist in the rootfs anyway

MAC_FILE="/persist/wifi/.macaddr"

if [ ! -f "$MAC_FILE" ]; then
    mkdir -p $(dirname $MAC_FILE)
    echo -n -e "\x00\x90\x4c" > "$MAC_FILE"
    head -c 3 /dev/urandom >> "$MAC_FILE"
fi

