#!/bin/sh
set -e

# Enable low power mode
echo 0 > /sys/module/lpm_levels_legacy/parameters/sleep_disabled

# Set CPU governor to schedutil (ramps up quickly for bursty workloads)
echo schedutil > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

# Disable three cores
echo 0        > /sys/devices/system/cpu/cpu1/online
echo 0        > /sys/devices/system/cpu/cpu2/online
echo 0        > /sys/devices/system/cpu/cpu3/online

# CPU IDLE Low Power Mode config
echo 1 > /sys/module/lpm_levels_legacy/system/cpu0/pc/suspend_enabled
echo 1 > /sys/module/lpm_levels_legacy/system/cpu0/standalone_pc/suspend_enabled
echo 1 > /sys/module/lpm_levels_legacy/system/cpu0/standalone_pc/idle_enabled
echo 1 > /sys/module/lpm_levels_legacy/system/cpu0/pc/idle_enabled
